site_name: 浙江大学23年春夏系统三实验
site_url: https://Parfaity.gitee.io/sys3lab-2023-stu/
repo_url: https://gitee.com/Parfaity/sys3lab-2023-stu
repo_name: sys3lab-2023-stu

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - 实验指导一: lab1.md
markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg